In [2]:
l1 = [1, 2, 3, 4]

In [3]:
l2 = [
    [1, 2, 3],
    [4, 5, 6]
]

In [4]:
[[j+2 for j in i] for i in l2]

[[3, 4, 5], [6, 7, 8]]

In [5]:
import numpy as np
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a2d = np.array([[1, 2, 3],
                [4, 5, 6]])
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3d = np.array([
    [[1, 2], [3, 4]
     ],
    [[5, 6], [7, 8]
     ]
])
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a3d.dtype

dtype('int64')

In [10]:
b = np.array([1, 2, 3, 4, 255], dtype=np.uint8)
b

array([  1,   2,   3,   4, 255], dtype=uint8)

In [11]:
np.arange(10, 15, 0.2)

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8])

In [12]:
np.arange(10, 15, 2, dtype=float)

array([10., 12., 14.])

In [13]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [14]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
b.ndim

2

In [16]:
a3d.ndim

3

In [17]:
ones = np.ones((2, 3), dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
ones*7

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
c = np.array([1, "2"])
c.dtype

dtype('<U21')

In [20]:
c

array(['1', '2'], dtype='<U21')

In [21]:
sevens = np.full((2, 3), 7)
sevens

array([[7, 7, 7],
       [7, 7, 7]])

In [22]:
empty = np.empty((4, 2))
empty

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
empty.ndim

2

In [24]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
data = np.array([1, 2], dtype = int)
ones = np.ones(2, dtype = int)
data + ones

array([2, 3])

In [28]:
a1 = np.array(1.6)
a1.shape

()

In [30]:
first = np.array([1, 2, 3], dtype = int)
second = np.array([[4], [5], [6]], dtype = int)
print(first.shape)
print(second.shape)

(3,)
(3, 1)


In [34]:
third = first*second
third

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [35]:
third[0, 1]

np.int64(8)

In [36]:
third[0:2, 0]

array([4, 5])

In [37]:
third[0:2][0]

array([ 4,  8, 12])

In [43]:
third[::2, ::2]

array([[ 4, 12],
       [ 6, 18]])